name: 'Add an issue link'
description: 'Use to add an issue link related to your pull requests.'
author: 'tktcorporation'
inputs:
  repo-token:
    description: 'A token of the repository. It can be passed with `{{ secrets.GITHUB_TOKEN }}`.'
    required: true
  branch-prefix:
    description: 'A prefix of the branch name for finding a related issue. Default: `issue-`'
    required: false
    dafault: 'issue-'
  position:
    description: '`top` or `bottom`. A position name of inserting issue link section. Default: `bottom`'
    required: false
    default: 'bottom'
  header:
    description: 'A header of issue link section. Default: `# Related issue`'
    required: false
    default: '# Related issue'
  resolve:
    description: '`true` or `false`. `true` to add "Resolve" prefix to an issue link. "Resolve" prefix close an related issue when the branch is merged. Default: `true`'
    required: false
    default: 'false'
  resolve-word:
    description: 'A word for "Resolve" prefix. Default: `Resolve`'
    required: false
    default: 'Resolve'
  repository:
    description: 'Repository name for using an other repository. (e.g. "tkt-actions/issue-links")'
    required: false
  link-style:
    description: '`body` or `comment`. `body` add an issue link by editing Pull Request body. `comment` add an issue link by creating comment to Pull Request. Default: `body`'
    required: false
    default: 'body'
  assign-pr-creator-to-issue:
    description: '`true` or `false`. `true` to automatically assign the pull request creator to the related issue. Default: `false`'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'link'
  color: 'gray-dark'
