name: 'Build and Push'
on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: npm install, build
        run: |
          npm install
          npm run build
      
      - name: Check diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m 'bot: build'
          git push
        if: steps.diff.outcome == 'failure'

