name: "Issue Link Comment (with resolve-word)"
on:
  pull_request:
    types: [opened]

jobs:
  issue-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add issue links with link-style option
        uses: ./
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          branch-prefix: ""
          resolve: "false"
          resolve-word: "release:"
          repository: "tktcorporation/tktcorporation"
          link-style: "comment"
