name: 'Issue Link Comment (with resolve-word)'
on:
  pull_request:
    types: [opened]

jobs:
  issue-link:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: issue link comment
        uses: ./
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          branch-prefix: '^'
          resolve: 'true'
          resolve-word: 'release:'
          link-style: 'comment'
