name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: npm install, build, lint and test
        run: |
          npm install
          npm run check
